version: 2
jobs:
  test_python:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      # - run:
      #     name: "Setup custom environment variables"
      #     command: |
      #       echo 'export $GIT_ROOT=$(git rev-parse --show-toplevel)' >> $BASH_ENV
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 -m pytest
            python3 -m pydocstyle DBImport/
      - store_artifacts:
          path: test-reports/
          destination: python_app
  test_git_commit:
    docker: 
      - image: circleci/node:10.0.0
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "package.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          command: |
            npm install
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules  # location depends on npm version
          key: node-v1-{{ .Branch }}-{{ checksum "package.json" }}
      - run: 
          command: |
            /bin/sh scripts/commitlint_range.sh
  test_mongodb:
    docker:
      - image: circleci/mongo:latest
    steps:
      - checkout
      - run:
          command:
            "mongo $MongoTestString --eval 'db.serverStatus()'"
            
            
workflows:
  version: 2
  build_and_test:
    jobs:
      - test_python
      - test_git_commit
      - test_mongodb
      