# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instructor.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import course_pb2 as course__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='instructor.proto',
  package='dbimport',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x10instructor.proto\x12\x08\x64\x62import\x1a\x0c\x63ourse.proto\"\xa2\x01\n\nInstructor\x12\x11\n\tfirstName\x18\x01 \x02(\t\x12\x10\n\x08lastName\x18\x02 \x02(\t\x12\x12\n\nmiddleName\x18\x03 \x01(\t\x12\x0f\n\x07website\x18\x04 \x01(\t\x12\r\n\x05\x65mail\x18\x05 \x01(\t\x12\x12\n\ndepartment\x18\x06 \x03(\t\x12\'\n\rrelatedCourse\x18\x07 \x03(\x0b\x32\x10.dbimport.Course'
  ,
  dependencies=[course__pb2.DESCRIPTOR,])




_INSTRUCTOR = _descriptor.Descriptor(
  name='Instructor',
  full_name='dbimport.Instructor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='firstName', full_name='dbimport.Instructor.firstName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lastName', full_name='dbimport.Instructor.lastName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='middleName', full_name='dbimport.Instructor.middleName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='website', full_name='dbimport.Instructor.website', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='dbimport.Instructor.email', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='department', full_name='dbimport.Instructor.department', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='relatedCourse', full_name='dbimport.Instructor.relatedCourse', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=207,
)

_INSTRUCTOR.fields_by_name['relatedCourse'].message_type = course__pb2._COURSE
DESCRIPTOR.message_types_by_name['Instructor'] = _INSTRUCTOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Instructor = _reflection.GeneratedProtocolMessageType('Instructor', (_message.Message,), {
  'DESCRIPTOR' : _INSTRUCTOR,
  '__module__' : 'instructor_pb2'
  # @@protoc_insertion_point(class_scope:dbimport.Instructor)
  })
_sym_db.RegisterMessage(Instructor)


# @@protoc_insertion_point(module_scope)
